name: Build and Package WallE-Downloader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller rarfile

    - name: Download Release.rar from DepotDownloaderMod
      run: |
        curl -L -o Release.rar "https://github.com/SteamAutoCracks/DepotDownloaderMod/releases/latest/download/Release.rar"

    - name: Extract Release.rar
      run: |
        mkdir extracted
        tar -xf Release.rar -C extracted || powershell -Command "Expand-Archive -Path Release.rar -DestinationPath extracted"

    - name: Copy DepotDownloaderMod files to DepotDownloaderMod/
      shell: bash
      run: |
        set -e
        DEPOT=$(find extracted -name "DepotDownloaderMod.exe" | head -n 1)
        if [ -z "$DEPOT" ]; then
          echo "DepotDownloaderMod.exe not found!"
          exit 1
        fi
        DEPOT_DIR=$(dirname "$DEPOT")
        mkdir -p DepotDownloaderMod
        cp -r "$DEPOT_DIR"/* DepotDownloaderMod/

    - name: Compile app.py to app.exe
      run: |
        pyinstaller --clean --noconsole --onefile --name app app.py

    - name: Prepare WallE-Downloader.zip
      run: |
        mkdir WallE-Downloader
        copy dist\app.exe WallE-Downloader\
        xcopy DepotDownloaderMod WallE-Downloader\DepotDownloaderMod /E /I /Y
        powershell -Command "Compress-Archive -Path WallE-Downloader -DestinationPath WallE-Downloader.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: WallE-Downloader
        path: WallE-Downloader.zip
