name: Build and Package WallE-Downloader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller rarfile

    - name: Install unrar
      run: sudo apt-get update && sudo apt-get install -y unrar

    - name: Download Release.rar from DepotDownloaderMod
      run: |
        curl -L -o Release.rar "https://github.com/SteamAutoCracks/DepotDownloaderMod/releases/latest/download/Release.rar"

    - name: Extract Release.rar
      run: |
        mkdir extracted
        unrar x -y Release.rar extracted/

    - name: Copy DepotDownloaderMod files to project root
      run: |
        set -e
        DEPOT=$(find extracted -name "DepotDownloaderMod.exe" | head -n 1)
        if [ -z "$DEPOT" ]; then
          echo "DepotDownloaderMod.exe not found!"
          exit 1
        fi
        DEPOT_DIR=$(dirname "$DEPOT")
        cp -r "$DEPOT_DIR"/* .

    - name: Compile app.py to app.exe
      run: |
        pyinstaller --noconsole --onefile app.py

    - name: Debug List dist folder
      run: ls -l dist

    - name: Prepare WallE-Downloader.zip
      run: |
        zip -r WallE-Downloader.zip dist/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: WallE-Downloader
        path: WallE-Downloader.zip
